
  openapi: 3.0.1
  info:
    title: User CRUD
    description:
      This is a sample crud server. You can find out more info at
      [http://localhost:3000/user](http://localhost:3000/user)
    version: 1.0.0
  tags:
    - name: user
      description: ICRUD OPERATION

  paths:
    /user:
      get:
        tags:
          - user
        summary: Find all users
        operationId: FindUsers
        responses:
          '200':
            description: successful
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:  
                        $ref: '#/components/schemas/User'
                    message:
                      type: string
                    code:
                      type: integer
          '404':
            description: Not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/404NotFound'
      post:
        tags:
          - user
        summary: Create a user
        operationId: CreateUser
        parameters:
          - name: data
            in: header
            description: values that need to be put
            required: true
            schema:
              $ref: '#/components/schemas/User'
        responses:
          '201':
            description: Created
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      $ref: "#/components/schemas/User"
                    message:
                      type: string
                      example: created
                    statusCode:
                      type: integer
                      example: 201
          '500':
            description: Internal Server Error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/500InternalServerError'
          '400':
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/400BadRequest'

    /user/{id}:
      get:
        tags:
          - user
        summary: Find user by id
        operationId: getUserById
        parameters:
          - name: id
            in: path
            description: 'The id that needs to be fetched.'
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      $ref: "#/components/schemas/User"
                    message:
                      type: string
                      example: Retrieved
                    statusCode:
                      type: integer
                      example: 200
          '400':
            description: Invalid username supplied
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/400BadRequest'
          '404':
            description: User not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/404NotFound'
      put:
        tags:
          - user
        summary: Updated user by id
        operationId: updateUser
        parameters:
          - name: id
            in: path
            description: id that need to be updated
            required: true
            schema:
              type: string
          - name: data
            in: header
            description: values that need to be put
            required: true
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                age:
                  type: integer
            example:
              {
                "name" : "tejas",
                "email" : "tejas@gmail.com",
                "phone" : "9876543210",
                "age" : 23
            }
        requestBody:
          description: Updated user object
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
          required: true
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      $ref: "#/components/schemas/User"
                    message:
                      type: string
                      example: created
                    statusCode:
                      type: integer
                      example: 201
          '500':
            description: Invalid id
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/500InternalServerError'
          '400':
            description: Bad request
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/400BadRequest'
      delete:
        tags:
          - user
        summary: Delete user by id
        operationId: DeleteUser
        parameters:
          - name: id
            in: path
            description: The id that needs to be deleted
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: integer
                      example: 2
                    message:
                      type: string
                      example: user deleted
                    statusCode:
                      type: integer
                      example: 201
          '500':
            description: Invalid id
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/500InternalServerError'
          '400':
            description: User data not found
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/400BadRequest'
  components:
    schemas:
      User:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 1
          username:
            type: string
            example: tejas
          email:
            type: string
            example: 'tejas@gmail.com.com'
          phone:
            type: string
            example: "9876543210"
          age:
            type: integer
            format: int32
            example: 23
      400BadRequest:
        type: object
        properties:
          errorCode  :
            type: integer
            example: 400
          errorMessage:
            type: string
            example: "error bad requests"
      404NotFound:
        type: object
        properties:
          errorCOde  :
            type: integer
            example: 404
          errorMessage:
            type: string
            example: "error not found"
      500InternalServerError:
        type: object
        properties:
          errorCode  :
            type: integer
            example: 500
          errorMessage:
            type: string
            example: "error bad requests"
