// Code generated by MockGen. DO NOT EDIT.
// Source: /home/raramuri/Desktop/go/src/user-curd/stores/Interface.go

// Package store is a generated GoMock package.
package store

import (
	reflect "reflect"
	model "user-curd/model"

	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// DeleteById mocks base method.
func (m *MockStore) DeleteById(Id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", Id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockStoreMockRecorder) DeleteById(Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockStore)(nil).DeleteById), Id)
}

// GetAll mocks base method.
func (m *MockStore) GetAll() ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStoreMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStore)(nil).GetAll))
}

// GetById mocks base method.
func (m *MockStore) GetById(Id int) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", Id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockStoreMockRecorder) GetById(Id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockStore)(nil).GetById), Id)
}

// InsertDetails mocks base method.
func (m *MockStore) InsertDetails(user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDetails", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertDetails indicates an expected call of InsertDetails.
func (mr *MockStoreMockRecorder) InsertDetails(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDetails", reflect.TypeOf((*MockStore)(nil).InsertDetails), user)
}

// UpdateById mocks base method.
func (m *MockStore) UpdateById(user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockStoreMockRecorder) UpdateById(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockStore)(nil).UpdateById), user)
}
